"""change migration for token

Revision ID: 2acc20069827
Revises: f2d5194a5331
Create Date: 2025-08-14 19:57:15.305085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acc20069827'
down_revision: Union[str, None] = 'f2d5194a5331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesstoken', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accesstoken', 'id')
    # ### end Alembic commands ###
