"""Rename UserTeam as Worker

Revision ID: 550edb8657d3
Revises: 7403d078c6c8
Create Date: 2025-08-15 18:45:38.733188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '550edb8657d3'
down_revision: Union[str, None] = '7403d078c6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_workers_team_id_team'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_workers_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_workers_user_id'))
    )
    op.create_index(op.f('ix_workers_team_id'), 'workers', ['team_id'], unique=False)
    op.drop_table('user_teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_teams',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_in_team', postgresql.ENUM('owner', 'admin', 'member', name='team_role'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_user_teams_team_id_team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_teams_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('pk_user_teams'))
    )
    op.drop_index(op.f('ix_workers_team_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
