"""change id in AccessToken model

Revision ID: 7403d078c6c8
Revises: efd4bcb87ef7
Create Date: 2025-08-15 11:43:42.700081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7403d078c6c8'
down_revision: Union[str, None] = 'efd4bcb87ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
