"""change USer model

Revision ID: 80dddfeb7d01
Revises: fea4846cb501
Create Date: 2025-08-14 08:35:49.880966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80dddfeb7d01'
down_revision: Union[str, None] = 'fea4846cb501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    team_role = sa.Enum('owner', 'admin', 'member', name='team_role')  # значения подставь свои
    team_role.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'period_end')
    op.drop_column('evaluation', 'period_start')
    op.drop_column('user', 'global_role')
    op.alter_column('user_teams', 'role_in_team',
               existing_type=sa.VARCHAR(length=20),
               type_=team_role,
               postgresql_using='role_in_team::text::team_role',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_teams', 'role_in_team',
               existing_type=sa.Enum('admin', 'manager', 'employee', name='team_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('user', sa.Column('global_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('evaluation', sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('evaluation', sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
