"""add role_in_team to Workers

Revision ID: 939539431ff0
Revises: 550edb8657d3
Create Date: 2025-08-15 18:51:57.025423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939539431ff0'
down_revision: Union[str, None] = '550edb8657d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('role_in_team', sa.Enum('admin', 'manager', 'employee', name='team_role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'role_in_team')
    # ### end Alembic commands ###
