"""delete unique user_id from Worker model

Revision ID: e3425578dc68
Revises: 4ec1ab120ff1
Create Date: 2025-08-19 13:38:58.135019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3425578dc68'
down_revision: Union[str, None] = '4ec1ab120ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'role_in_team',
               existing_type=postgresql.ENUM('admin', 'manager', 'employee', name='team_role'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_workers_user_id'), 'workers', type_='unique')
    op.create_unique_constraint('uq_worker_user_team', 'workers', ['user_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_worker_user_team', 'workers', type_='unique')
    op.create_unique_constraint(op.f('uq_workers_user_id'), 'workers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workers', 'role_in_team',
               existing_type=postgresql.ENUM('admin', 'manager', 'employee', name='team_role'),
               server_default=sa.text("'employee'::team_role"),
               existing_nullable=False)
    # ### end Alembic commands ###
