"""change User model

Revision ID: f2d5194a5331
Revises: 7c23ed63bd63
Create Date: 2025-08-14 19:15:08.912632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import TIMESTAMPAware


# revision identifiers, used by Alembic.
revision: str = 'f2d5194a5331'
down_revision: Union[str, None] = '7c23ed63bd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstoken',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=43), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_accesstoken_user_id_user'), ondelete='cascade'),
        sa.PrimaryKeyConstraint("token", name=op.f('pk_accesstoken'))
    ) 
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    # ### end Alembic commands ###
